# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d38c60b33dcab3e13c0741f8b425e51156a0411208535324aa1d2c1633a552b4aa89e3c4fe299b9e67732f18f9d3bef871306b8a2513acbe2b082866ca4de3c

test:
  secret_key_base: 7a600490e5b91fe308e02d2d4631b25012df1e418000c3ae08df55152080e6dca2cf3a60b218c5e756c75ffce0c55e91971c68e2c11944918baa43a1b38308e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
